# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration

require 'untied'
require 'ruby-debug'
require 'active_record'

ar_config = { :test => { :adapter => 'sqlite3', :database => ":memory:" } }
ActiveRecord::Base.configurations = ar_config
ActiveRecord::Base.establish_connection(ActiveRecord::Base.configurations[:test])

ActiveRecord::Schema.define do
  create_table :posts, :force => true do |t|
    t.string :title
  end
  create_table :users, :force => true do |t|
    t.string :name
  end
end

class User < ActiveRecord::Base; end
class Post < ActiveRecord::Base; end

Untied.configure do |config|
  config.service_name = "core"
end

RSpec.configure do |config|
  config.treat_symbols_as_metadata_keys_with_true_values = true
  config.run_all_when_everything_filtered = true
  config.filter_run :focus

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = 'random'
end
