# A sample Gemfile
source "https://rubygems.org"

gem "goliath"
gem "em-synchrony"
gem "sqlite3"
gem "activerecord"
gem "untied", :path  => '/Users/guiocavalcanti/workspace/work/untied-observer'
gem "rake"
