$: << File.dirname(__FILE__)

require "bundler/setup"
require "untied"
require "untied-consumer"

require "./observer"

# Enabling the observer defined in observer.rb
Untied::Consumer.configure do |c|
  c.observers = [Observer]
end

load "untied-consumer/tasks/untied.tasks"
