$: << File.dirname(__FILE__)

require "bundler/setup"
require "untied"

require "./observer"

# Enabling the observer defined in observer.rb
Untied::Consumer.observers = [Observer]

load "untied/tasks/untied.tasks"
